# Generated by Django 4.1.7 on 2023-08-12 09:53

import cloudinary.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='description', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='product_image'),
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(default='product label', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
