# Generated by Django 4.1.7 on 2023-08-12 13:51

from django.db import migrations, models
import django.db.models.deletion
import wagha.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagha', '0003_color_material_rating_size_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(default=wagha.models.Product.get_default_size, on_delete=django.db.models.deletion.CASCADE, to='wagha.size'),
        ),
    ]
