# Generated by Django 4.1.7 on 2023-08-12 14:03

from django.db import migrations, models
import django.db.models.deletion
import wagha.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagha', '0004_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(default=wagha.models.Product.get_default_material, on_delete=django.db.models.deletion.CASCADE, to='wagha.material'),
        ),
    ]
