# Generated by Django 4.1.7 on 2023-08-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagha', '0006_remove_product_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='wagha.tag'),
        ),
    ]
