# Generated by Django 4.1.7 on 2023-08-20 08:45

import cloudinary.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagha', '0009_alter_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='advertisement_image')),
                ('label', models.CharField(default='color', max_length=200)),
            ],
        ),
    ]
