# Generated by Django 4.1.7 on 2023-09-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagha', '0010_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
