# Generated by Django 4.1.7 on 2023-11-26 16:19

from django.db import migrations, models
import django.db.models.deletion
import wagha.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagha', '0011_size_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(default=wagha.models.Product.get_default_color, on_delete=django.db.models.deletion.CASCADE, to='wagha.color'),
        ),
    ]
